# Generated by Django 4.2.1 on 2023-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_avatar_remove_user_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.TextField(default=0, unique=True),
        ),
    ]
