# Generated by Django 4.0.10 on 2023-05-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
        ('wiki_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='title_id',
            field=models.ManyToManyField(related_name='wiki_detail', to='wiki_detail.wiki_detail'),
        ),
    ]
