# Generated by Django 4.2.1 on 2023-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki_detail", "0002_rename_name_wiki_detail_title"),
        ("wiki", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wiki",
            name="title_id",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="wiki_detail",
                to="wiki_detail.wiki_detail",
            ),
        ),
    ]
