# Generated by Django 4.2.1 on 2023-05-17 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wiki_detail", "0002_rename_name_wiki_detail_title"),
        ("wiki", "0003_alter_wiki_title_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wiki",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wiki",
            name="title_id",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wiki", to="wiki_detail.wiki_detail"
            ),
        ),
    ]
