databases:
  - name: AjouWiki
    databaseName: AjouWiki
    user: AjouWiki
    region: singapore
    plan: free

services:
  - type: web
    name: AjouWiki
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AjouWiki
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4  