# Generated by Django 4.0.10 on 2023-05-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiki_detail',
            old_name='name',
            new_name='title',
        ),
    ]
